#ifndef CYGONCE_PKGCONF_REDBOOT_H
#define CYGONCE_PKGCONF_REDBOOT_H
/*
 * File <pkgconf/redboot.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#include <pkgconf/hal.h>
#define CYGSEM_REDBOOT_ELF 1
#define CYGINT_REDBOOT_LOAD_METHOD 2
#define CYGINT_REDBOOT_LOAD_METHOD_2
#define CYGNUM_REDBOOT_CMD_LINE_EDITING 16
#define CYGNUM_REDBOOT_CMD_LINE_EDITING_16
#define CYGBLD_BUILD_REDBOOT_WITH_CKSUM 1
#define CYGBLD_BUILD_REDBOOT_WITH_MFILL 1
#define CYGBLD_BUILD_REDBOOT_WITH_MCMP 1
#define CYGBLD_BUILD_REDBOOT_WITH_DUMP 1
#define CYGBLD_BUILD_REDBOOT_WITH_CACHES 1
#define CYGBLD_BUILD_REDBOOT_WITH_EXEC 1
#define CYGPKG_REDBOOT_NETWORKING 1
#define CYGSEM_REDBOOT_NET_TFTP_DOWNLOAD 1
/*
#define CYGSEM_REDBOOT_NET_HTTP_DOWNLOAD 1
*/
#define CYGDAT_REDBOOT_DEFAULT_IP_ADDR 192, 168, 0, 1
#define CYGSEM_REDBOOT_DEFAULT_NO_BOOTP 1
#define CYGSEM_REDBOOT_NETWORKING_USE_GATEWAY 1
#define CYGDAT_REDBOOT_DEFAULT_GATEWAY_IP_ADDR 192, 168, 0, 1
#define CYGDAT_REDBOOT_DEFAULT_IP_ADDR_MASK 255, 255, 255, 0
#define CYGNUM_REDBOOT_NETWORKING_TCP_PORT 9000
#define CYGNUM_REDBOOT_NETWORKING_TCP_PORT_9000
#define CYGNUM_REDBOOT_NETWORKING_MAX_PKTBUF 4
#define CYGNUM_REDBOOT_NETWORKING_MAX_PKTBUF_4
/*
#define CYGPKG_REDBOOT_NETWORKING_DNS 1
#define CYGPKG_REDBOOT_NETWORKING_DNS_IP 0.0.0.0
*/
#define CYGNUM_REDBOOT_NETWORKING_DNS_TIMEOUT 10
#define CYGNUM_REDBOOT_NETWORKING_DNS_TIMEOUT_10
#define CYGNUM_REDBOOT_DEFAULT_NETWORK_DEVICE 0
#define CYGNUM_REDBOOT_DEFAULT_NETWORK_DEVICE_0
#define CYGPKG_REDBOOT_ANY_CONSOLE 1
#define CYGSEM_REDBOOT_VARIABLE_BAUD_RATE 1
#define CYGPKG_REDBOOT_MAX_CMD_LINE 256
#define CYGPKG_REDBOOT_MAX_CMD_LINE_256
#define CYGNUM_REDBOOT_CLI_IDLE_TIMEOUT 10
#define CYGNUM_REDBOOT_CLI_IDLE_TIMEOUT_10
#define CYGNUM_REDBOOT_LOAD_ZLIB_BUFFER 64
#define CYGNUM_REDBOOT_LOAD_ZLIB_BUFFER_64
#define CYGSEM_REDBOOT_VALIDATE_USER_RAM_LOADS 1
#define CYGNUM_REDBOOT_BOOT_SCRIPT_TIMEOUT_RESOLUTION 1000
#define CYGNUM_REDBOOT_BOOT_SCRIPT_DEFAULT_TIMEOUT 2
/*
#define CYGPKG_REDBOOT_FLASH 1
#define CYGBLD_REDBOOT_MIN_IMAGE_SIZE 0x40000
#define CYGBLD_REDBOOT_MIN_IMAGE_SIZE_0x40000
#define CYGBLD_REDBOOT_FLASH_BOOT_OFFSET 0
#define CYGBLD_REDBOOT_FLASH_BOOT_OFFSET_0
#define CYGNUM_REDBOOT_FLASH_RESERVED_BASE 0
#define CYGNUM_REDBOOT_FLASH_RESERVED_BASE_0
#define CYGSEM_REDBOOT_FLASH_LOCK_SPECIAL 1
#define CYGSEM_REDBOOT_FIS_CRC_CHECK 1
#define CYGINT_REDBOOT_ARM_FLASH_SIB_SUPPORTED 0
#define CYGINT_REDBOOT_ARM_FLASH_SIB_SUPPORTED_0
#define CYGFUN_REDBOOT_BOOT_SCRIPT 1
#define CYGDAT_REDBOOT_DEFAULT_BOOT_SCRIPT "boot;exec -r 0x00a00000 0x01008000\n"
#define CYGNUM_REDBOOT_BOOT_SCRIPT_TIMEOUT_RESOLUTION 1000
#define CYGNUM_REDBOOT_BOOT_SCRIPT_TIMEOUT_RESOLUTION_1000
#define CYGNUM_REDBOOT_BOOT_SCRIPT_DEFAULT_TIMEOUT 2
#define CYGNUM_REDBOOT_BOOT_SCRIPT_DEFAULT_TIMEOUT_2
*/
#define CYGSEM_REDBOOT_BSP_SYSCALLS 1
#define CYGSEM_REDBOOT_BSP_SYSCALLS_GPROF 1

#endif
