#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_ARM current
#define CYGPKG_HAL_ARM_current
#define CYGNUM_HAL_ARM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_XSCALE_CORE current
#define CYGPKG_HAL_ARM_XSCALE_CORE_current
#define CYGNUM_HAL_ARM_XSCALE_CORE_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_XSCALE_CORE_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_XSCALE_CORE_VERSION_RELEASE -1
#define CYGPKG_HAL_ARM_XSCALE_IXP425 current
#define CYGPKG_HAL_ARM_XSCALE_IXP425_current
#define CYGNUM_HAL_ARM_XSCALE_IXP425_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_XSCALE_IXP425_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_XSCALE_IXP425_VERSION_RELEASE -1
#define CYGBLD_HAL_ARM_VAR_IO_H
#define CYGPKG_HAL_ARM_XSCALE_GRG current
#define CYGPKG_HAL_ARM_XSCALE_GRG_current
#define CYGNUM_HAL_ARM_XSCALE_GRG_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_ARM_XSCALE_GRG_VERSION_MINOR -1
#define CYGNUM_HAL_ARM_XSCALE_GRG_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_arm.h>
#define CYGBLD_HAL_VARIANT_H  <pkgconf/hal_arm_xscale_ixp425.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_arm_xscale_grg.h>
#define CYG_HAL_STARTUP ROMRAM
#define CYG_HAL_STARTUP_ROMRAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_arm_xscale_grg_romram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_arm_xscale_grg_romram.h>

#define CYGPKG_IO_PCI current
#define CYGPKG_IO_PCI_current
#define CYGNUM_IO_PCI_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_PCI_VERSION_MINOR -1
#define CYGNUM_IO_PCI_VERSION_RELEASE -1
/*
#define CYGPKG_DEVS_ETH_INTEL_I82559 current
#define CYGPKG_DEVS_ETH_INTEL_I82559_current
#define CYGNUM_DEVS_ETH_INTEL_I82559_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_ETH_INTEL_I82559_VERSION_MINOR -1
#define CYGNUM_DEVS_ETH_INTEL_I82559_VERSION_RELEASE -1
*/
#define CYGBLD_DEVS_ETH_DEVICE_H <pkgconf/devs_eth_intel_i82559.h>
#define CYGPKG_DEVS_ETH_ARM_GRG_I82559 current
#define CYGPKG_DEVS_ETH_ARM_GRG_I82559_current
#define CYGNUM_DEVS_ETH_ARM_GRG_I82559_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_ETH_ARM_GRG_I82559_VERSION_MINOR -1
#define CYGNUM_DEVS_ETH_ARM_GRG_I82559_VERSION_RELEASE -1
/***** ethernet driver proc output start *****/
#define CYGDAT_DEVS_ETH_INTEL_I82559_INL <cyg/io/grg_i82559.inl>
#define CYGDAT_DEVS_ETH_INTEL_I82559_CFG <pkgconf/devs_eth_arm_grg_i82559.h>
/*****  ethernet driver proc output end  *****/
#define CYGPKG_DEVS_FLASH_STRATA current
#define CYGPKG_DEVS_FLASH_STRATA_current
#define CYGNUM_DEVS_FLASH_STRATA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_STRATA_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_STRATA_VERSION_RELEASE -1
#define CYGPKG_DEVS_FLASH_GRG current
#define CYGPKG_DEVS_FLASH_GRG_current
#define CYGNUM_DEVS_FLASH_GRG_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_FLASH_GRG_VERSION_MINOR -1
#define CYGNUM_DEVS_FLASH_GRG_VERSION_RELEASE -1
/***** grg flash driver proc output start *****/
#define CYGDAT_DEVS_FLASH_STRATA_INL <cyg/io/grg_strataflash.inl>
#define CYGDAT_DEVS_FLASH_STRATA_CFG <pkgconf/devs_flash_grg.h>
/*****  GRG flash driver proc output end  *****/
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_REDBOOT current
#define CYGPKG_REDBOOT_current
#define CYGNUM_REDBOOT_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_REDBOOT_VERSION_MINOR -1
#define CYGNUM_REDBOOT_VERSION_RELEASE -1
#define CYGNUM_HAL_VIRTUAL_VECTOR_AUX_CHANNELS 1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_NS_DNS current
#define CYGPKG_NS_DNS_current
#define CYGNUM_NS_DNS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_NS_DNS_VERSION_MINOR -1
#define CYGNUM_NS_DNS_VERSION_RELEASE -1
#define CYGPKG_CRC current
#define CYGPKG_CRC_current
#define CYGNUM_CRC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_CRC_VERSION_MINOR -1
#define CYGNUM_CRC_VERSION_RELEASE -1
#define CYGPKG_IO_FLASH current
#define CYGPKG_IO_FLASH_current
#define CYGNUM_IO_FLASH_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_FLASH_VERSION_MINOR -1
#define CYGNUM_IO_FLASH_VERSION_RELEASE -1
#define CYGPKG_IO_ETH_DRIVERS current
#define CYGPKG_IO_ETH_DRIVERS_current
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_ETH_DRIVERS_VERSION_MINOR -1
#define CYGNUM_IO_ETH_DRIVERS_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
/*
#define CYGPKG_COMPRESS_ZLIB current
#define CYGPKG_COMPRESS_ZLIB_current
#define CYGNUM_COMPRESS_ZLIB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_COMPRESS_ZLIB_VERSION_MINOR -1
#define CYGNUM_COMPRESS_ZLIB_VERSION_RELEASE -1
*/

#define CYGPKG_DEVS_ETH_INTEL_NPE v1_0
#define CYGPKG_DEVS_ETH_INTEL_NPE_v1_0
#define CYGNUM_DEVS_ETH_INTEL_NPE_VERSION_MAJOR 1
#define CYGNUM_DEVS_ETH_INTEL_NPE_VERSION_MINOR 0
#define CYGNUM_DEVS_ETH_INTEL_NPE_VERSION_RELEASE -1
#define CYGPKG_DEVS_ETH_ARM_GRG_NPE v1_0
#define CYGPKG_DEVS_ETH_ARM_GRG_NPE_v1_0
#define CYGNUM_DEVS_ETH_ARM_GRG_NPE_VERSION_MAJOR 1
#define CYGNUM_DEVS_ETH_ARM_GRG_NPE_VERSION_MINOR 0
#define CYGNUM_DEVS_ETH_ARM_GRG_NPE_VERSION_RELEASE -1
/***** ethernet driver proc output start *****/
#define CYGDAT_DEVS_ETH_INTEL_NPE_INL <cyg/io/grg_npe.inl>
#define CYGDAT_DEVS_ETH_INTEL_NPE_CFG <pkgconf/devs_eth_arm_grg_npe.h>
/*****  ethernet driver proc output end  *****/

#endif
